---
title: "G19 Machine Learning Workshop"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Welcome

These are the preparation and teaching material website for the GLEON 19 meeting Machine Learning
workshop. 

## Setting up R

First, we need to setup R and an editor for you. For R there is really no choice. For an R editor
there are many, but the most common to use is RStudio. 

Steps: 

1. [Download the latest version of R if you don't already have it](https://cran.r-project.org/). Install it. 
2. [Download the latest version of RStudio if you don't have it](https://www.rstudio.com/products/rstudio/download/#download).
Install it. 
3. Verify that you can run RStudio. 



## Get the Workshop Example Materials

The workshop example scripts and data have been provided to make it 
easier to follow along with the instructor. [Download the most recent
materials here](https://github.com/lawinslow/machine_learning/archive/master.zip). 
Once downloaded, unzip the contents and put the folder somewhere easily accessible. 


## Installing Needed Packages

We will use a wide variety of R packages today during the workshop. They will take a little bit of time 
to download and install, so go ahead and do that whenever you are ready. 



